name = "CossioJuliaRegistry"
uuid = "9ead806a-b9fe-4182-9efa-aa6064b82dfe"
repo = "https://github.com/cossio/CossioJuliaRegistry"
description = "My public Julia registry"

[packages]
04583435-db98-4dac-86c0-bf703bfe1daf = { name = "NeuralHMMs2024", path = "N/NeuralHMMs2024" }
04d9922e-d2ea-4396-8346-a9e63bc8ac15 = { name = "ProjectTomlFormatter", path = "P/ProjectTomlFormatter" }
0601a985-4ee2-4e64-98ce-33fb04e53a0e = { name = "AdvWW", path = "A/AdvWW" }
0a44db02-9f29-404b-a163-745dc29c0aa6 = { name = "PCloudPublicLinks", path = "P/PCloudPublicLinks" }
0cf600e5-c0f5-4f4c-a3cb-80a0fa474752 = { name = "BinaryLogisticRegression", path = "B/BinaryLogisticRegression" }
10eba040-4fa0-471e-8958-333e2d4ab5c4 = { name = "DuplicateFiles", path = "D/DuplicateFiles" }
12e6b396-7db5-4506-8cb6-664a4fe1e50e = { name = "RestrictedBoltzmannMachines", path = "R/RestrictedBoltzmannMachines" }
18c5b9ad-20a6-4587-bcd1-d3f661342d19 = { name = "RBM_Hidden_Unit_Importance", path = "R/RBM_Hidden_Unit_Importance" }
19b89899-3127-41f3-9f12-80db529951d5 = { name = "BlockRBMs", path = "B/BlockRBMs" }
1b3c2205-da69-4893-b2df-717075b12251 = { name = "LogStatFunctions", path = "L/LogStatFunctions" }
200c354f-c975-4e3e-8a54-35c3e28e1157 = { name = "KAnsatzRBMs", path = "K/KAnsatzRBMs" }
275cd14a-065f-44bb-ab7a-e1328a0f1819 = { name = "Pfam", path = "P/Pfam" }
2814ae69-ac9a-473b-90f0-2183b26fd128 = { name = "BioSequencesOneHot", path = "B/BioSequencesOneHot" }
2b13551f-3605-4edc-95cf-7fb1224558b0 = { name = "SamApp", path = "S/SamApp" }
2b3394db-9f9c-454f-a26a-0ad872321417 = { name = "LatticeProteins", path = "L/LatticeProteins" }
2f9af0fd-2043-4477-827d-59df7d24c0cf = { name = "RBMsEffectiveContacts", path = "R/RBMsEffectiveContacts" }
32bf53d6-29b3-4097-a256-fb928b83f926 = { name = "DiffRBMs", path = "D/DiffRBMs" }
38c5b72b-a3f0-437e-9f79-f3da4655de63 = { name = "Rfam", path = "R/Rfam" }
3e22dfff-eee4-477b-ac6a-6f7f49e5ccf0 = { name = "Logomaker", path = "L/Logomaker" }
4026178e-4dd9-40a6-aa83-a43e8a4150db = { name = "RBM_Spins_2_Data_Points_202307", path = "R/RBM_Spins_2_Data_Points_202307" }
44a33129-0204-4b4f-90cd-7d555cfcf046 = { name = "BiTrainedRBMs", path = "B/BiTrainedRBMs" }
460b0459-f81d-40f2-a460-3486927c7399 = { name = "OneHot", path = "O/OneHot" }
471aab8e-00ab-4b25-950a-324b7977a398 = { name = "SimpleLinearRegression", path = "S/SimpleLinearRegression" }
4aa08641-d763-4623-9c5b-cef742500064 = { name = "Infernal", path = "I/Infernal" }
4b4759f1-b06d-4e46-9a15-fec13d1dd0af = { name = "StackedTempering", path = "S/StackedTempering" }
4e7460e3-fd1b-4f88-90fa-49c1b80b3e77 = { name = "CudaRBMs", path = "C/CudaRBMs" }
4f043ecb-e21b-455c-9fdf-d7072a819848 = { name = "TMscore", path = "T/TMscore" }
4fd60db2-ef25-4635-ac1e-32b2ac4c6c94 = { name = "DucongeSELEXTestData", path = "D/DucongeSELEXTestData" }
510d54db-c4c5-42e5-a23f-692f13fe7033 = { name = "Phylip", path = "P/Phylip" }
5155ca0f-65d6-4a7f-9007-f2236b8a1a58 = { name = "GapRBMs", path = "G/GapRBMs" }
57af301a-a58c-11e9-1f68-193042cecb35 = { name = "TruncatedNormal", path = "T/TruncatedNormal" }
588a0096-e0a1-4de3-978b-1ea682c721a8 = { name = "MyAppConfigs", path = "M/MyAppConfigs" }
59c5aa83-900c-4c4d-b6cc-c9bbbf32a260 = { name = "HMMER", path = "H/HMMER" }
5c1707b9-8742-4973-ad94-73a991805081 = { name = "K2RSB2024", path = "K/K2RSB2024" }
5c8d321f-d88f-4112-b4bc-67901fc2de0a = { name = "AdvRBMs", path = "A/AdvRBMs" }
5d765a50-bc5e-4a6c-9695-cf9e14bd67e3 = { name = "GaussianSinhCosh", path = "G/GaussianSinhCosh" }
5e47bd60-7715-431b-887a-edff83ed7926 = { name = "FastPCD", path = "F/FastPCD" }
5fe15cf2-0931-46e2-8153-23dc94d82379 = { name = "TwoDataPointsAnsatzSpinRBM", path = "T/TwoDataPointsAnsatzSpinRBM" }
61b0d15e-aa6e-446e-a483-edda46eb69d6 = { name = "StackedRBMs", path = "S/StackedRBMs" }
64a072fb-ee9f-4297-92fa-03899ca5ed3d = { name = "Tail2Front2", path = "T/Tail2Front2" }
6c386691-cfc4-46ad-8ebc-0b04e07c7d7e = { name = "SimpleConvRBMs", path = "S/SimpleConvRBMs" }
723ee7ca-8220-4cb6-9f2e-031e2886e2e7 = { name = "IsingModels", path = "I/IsingModels" }
753563aa-0f64-43bc-bd25-171000cdc6b1 = { name = "GithubQueries", path = "G/GithubQueries" }
7673ebd9-f02d-46dd-b879-08aafde2f01b = { name = "LocalStore", path = "L/LocalStore" }
77448240-233f-471d-9874-cd3eeb30077f = { name = "MyPlutoHelper", path = "M/MyPlutoHelper" }
850d8bc9-49d3-40ec-92e0-8655eafbf481 = { name = "KakiPkg2", path = "K/KakiPkg2" }
86a1cd04-caa9-4a24-a00b-0f668856e5ae = { name = "UndersampledBMs2024", path = "U/UndersampledBMs2024" }
88dc9d0e-45ea-4ad8-8ef4-d576c082fadd = { name = "SpringSeries", path = "S/SpringSeries" }
896d28fb-f16f-41fb-b660-35006467145e = { name = "LowRankRBMs", path = "L/LowRankRBMs" }
8983b433-9f7e-480f-b58a-217368ada2eb = { name = "TeacherStudentLowRankRBM", path = "T/TeacherStudentLowRankRBM" }
8b707c2e-8f88-4d0c-96e7-f8e5439ca0fb = { name = "VecTails", path = "V/VecTails" }
90902b46-5383-4c97-8f8a-bddf608a7bc6 = { name = "ROCCurves", path = "R/ROCCurves" }
937310f5-01c8-40cc-bba5-d60347cf23b4 = { name = "GistArtifactsHelper", path = "G/GistArtifactsHelper" }
95861e33-42fb-4e14-ae5f-03a85d34826c = { name = "ContrastiveDivergenceRBM", path = "C/ContrastiveDivergenceRBM" }
982e605e-fd7d-4c5d-a517-224ed2053a87 = { name = "ZebrafishHMM2023", path = "Z/ZebrafishHMM2023" }
a10097c8-9f5b-4030-a7d7-d11adc5c7381 = { name = "FASTXDoReaders", path = "F/FASTXDoReaders" }
a8ff5cc1-b4eb-4372-aeb2-8e274b603cc8 = { name = "LogBinomial", path = "L/LogBinomial" }
aa288701-83bc-4fd3-aba5-ac3dd7693cd5 = { name = "FactoredMatrices", path = "F/FactoredMatrices" }
ab373e77-9f79-45f8-97ab-fd137f9b486f = { name = "FastTree", path = "F/FastTree" }
adc085a9-6b67-43ec-8d2e-d860834cc8d5 = { name = "SpinRBMs", path = "S/SpinRBMs" }
ae06e78d-6dbf-4dd2-8442-f8685bffd6c3 = { name = "AdaptiveParallelTemperedRBMs", path = "A/AdaptiveParallelTemperedRBMs" }
bade5a7f-a4d3-4012-9306-1f52b703818b = { name = "MyRegistrator", path = "M/MyRegistrator" }
bcd408f2-95f5-489e-9934-d251842dc866 = { name = "PottsGumbelRBMLayers", path = "P/PottsGumbelRBMLayers" }
bd9b4ad5-e63c-47bb-8129-8772c89b08fb = { name = "CossioPkgTemplates", path = "C/CossioPkgTemplates" }
bda25098-0934-4bae-a887-3b2fb620d6b6 = { name = "KakiPkg", path = "K/KakiPkg" }
bf079423-f436-4d7e-85be-dd05ede77fe7 = { name = "SHAPE_MaP_LogNormal_NegBinom_Indep", path = "S/SHAPE_MaP_LogNormal_NegBinom_Indep" }
c02aafcb-3c77-412c-b3fd-defee07fbcfd = { name = "SHAPE_MaP_LogNormal", path = "S/SHAPE_MaP_LogNormal" }
c1d5de99-3441-47e2-85af-8ce5ee9923a2 = { name = "DampedUpdates", path = "D/DampedUpdates" }
c8d9fdc7-1808-4fba-8c97-f848504396a5 = { name = "StandardizedRestrictedBoltzmannMachines", path = "S/StandardizedRestrictedBoltzmannMachines" }
cc4d5295-06e1-420e-aa8e-2bd5f6f39c3c = { name = "TensorFactorizations", path = "T/TensorFactorizations" }
d015f569-cd2a-4d71-b962-240f6358815c = { name = "NegativeGammaDistributions", path = "N/NegativeGammaDistributions" }
d213bb01-7728-4912-8b4c-05bc355976fe = { name = "SimpleDiffRBMs", path = "S/SimpleDiffRBMs" }
d4206499-9796-4f58-8a56-acae5424fe35 = { name = "ConditionalSwaps", path = "C/ConditionalSwaps" }
d7583257-2d3b-486d-b93f-702fcfec9f7b = { name = "MetropolisRules", path = "M/MetropolisRules" }
d75ee8c3-a7b8-40a0-a13d-4e87fb3391ab = { name = "PhageNegBinom", path = "P/PhageNegBinom" }
d76020e8-6658-45fa-bb6d-0aaddbb4b5e5 = { name = "RestrictedBoltzmannMachinesHDF5", path = "R/RestrictedBoltzmannMachinesHDF5" }
dc9b9f13-b6c1-41c2-bb2d-deda4a73e383 = { name = "DT_NIPS_20230511", path = "D/DT_NIPS_20230511" }
def70c09-f69f-4396-afd1-e8507a6dddbf = { name = "CenteredRBMs", path = "C/CenteredRBMs" }
df016029-629c-4086-9316-c1caa86717d0 = { name = "Ab4v2", path = "A/Ab4v2" }
e765fd00-6e60-4ef4-b5a1-61aabe4eb58a = { name = "Rank2AnsatzRBMs", path = "R/Rank2AnsatzRBMs" }
ec3f1a63-6c3e-4f00-909b-6a02b9e7293b = { name = "GumbelTrick", path = "G/GumbelTrick" }
eedbd132-2e7d-4d7f-8b5e-3472db8bad43 = { name = "ElementarySymmetricPolynomials", path = "E/ElementarySymmetricPolynomials" }
ef4fae33-fc79-49a8-89d3-d788f6f5c5d6 = { name = "ICLR20230923_StackedTempering", path = "I/ICLR20230923_StackedTempering" }
f2fe0091-2492-4230-8585-a9074f4fb3e3 = { name = "RBMsLocalMetropolis", path = "R/RBMsLocalMetropolis" }
f33293c1-5d97-46a9-b004-6e9c52dae28f = { name = "RBMs_K_20231009", path = "R/RBMs_K_20231009" }
f4818a02-fb31-488d-84ee-227add8f92b8 = { name = "RBMsAnnealedImportanceSampling", path = "R/RBMsAnnealedImportanceSampling" }
f652b08b-70c7-4146-a29e-61b6e13bacd7 = { name = "PhyML", path = "P/PhyML" }
f6f8b1ef-ccdd-40fd-b661-a25ba26d3870 = { name = "ParallelTemperingRBMsCho2010", path = "P/ParallelTemperingRBMsCho2010" }
f80e20bb-2661-4ac8-90b2-62c90882fd5a = { name = "LeNet5Flux", path = "L/LeNet5Flux" }
f877af3d-8d8e-4a62-8140-d28779695e4f = { name = "Celeba", path = "C/Celeba" }
f9ac534b-7a4d-4050-9788-7568e13bfb5a = { name = "KakiTelegramBot", path = "K/KakiTelegramBot" }
fc28dbd6-0008-41b8-97c8-e90c0437b90e = { name = "PhageTree", path = "P/PhageTree" }
ff22355f-df7d-420f-b7ab-250fa0a7996a = { name = "Ab4App", path = "A/Ab4App" }
ff6f32c6-25e8-4023-ad15-765665b8cc5b = { name = "SHAPE_MaP_LogNormal_Poisson_Indep", path = "S/SHAPE_MaP_LogNormal_Poisson_Indep" }
ff7337f9-42d2-4134-a6d5-1486ab687e52 = { name = "SpaceRBMs", path = "S/SpaceRBMs" }
